// src/components/SelectableList.tsx
import { Component } from 'react'
import { Divider, Grid, List, ListItem, ListItemButton, ListItemText, ListSubheader } from '@mui/material'

interface SelectableListProps {
    items: string[]
    onSelectItem: any
    selectedItem: string
    title: string
}

interface SelectableListState {
    onSelectItem: any
}

export default class SelectableList extends Component<SelectableListProps, SelectableListState> {
    constructor(props: SelectableListProps) {
        super(props)
        this.state = {
            onSelectItem: props.onSelectItem
        }
    }

    render() {
        return (
            <Grid item>
                <List dense
                    disablePadding
                    sx={{
                        maxHeight: this.getHeight(),
                        overflowY: "auto"
                    }}>
                    <ListSubheader>
                        {this.props.title}
                        <Divider />
                    </ListSubheader>
                    {this.props.items?.map(item => (
                        <ListItem disablePadding key={item}>
                            <ListItemButton
                                onClick={_ => this.updateSelected(item)}
                                selected={this.props.selectedItem == item}>
                                <ListItemText primary={item} />
                            </ListItemButton>
                        </ListItem>
                    ))}
                </List>
            </Grid>
        )
    }

    getHeight(): number {
        var height = window.innerHeight
        if (document.getElementById("clip-preview") != null) {
            height -= (document.getElementById("clip-preview") as HTMLCanvasElement).height
        }
        if (document.getElementById("navbar") != null) {
            height -= (document.getElementById("navbar") as HTMLElement).clientHeight
        }
        height -= 64
        height = Math.max(height, 256)
        return height
    }

    updateSelected(item: string) {
        if (this.props.onSelectItem != null) {
            this.props.onSelectItem(item)
        }
    }
}

// src/components/SelectableList.vue
<template>
  <div class="selectable-list">
    <div class="row">
      <q-list class="list">
        <q-item>
          <q-item-section>
            <q-item-label>{{ props.title }}</q-item-label>
          </q-item-section>
        </q-item>
        <q-item v-for="item in props.items" :key="item" clickable v-ripple @click="selectItem(item)">
          <q-item-section>
            <q-item-label>{{ item }}</q-item-label>
          </q-item-section>
        </q-item>
      </q-list>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';

export interface SelectableListProps {
  items: Array<string>;
  onSelectItem: (item: string) => void;
  selectedItem: string;
  title: string;
}

const emit = defineEmits(['selectItem']);

const props = defineProps<SelectableListProps>();

const getHeight = computed((): number => {
  var height = window.innerHeight;
  const clipPreview = document.getElementById('clip-preview');
  if (clipPreview) {
    height -= clipPreview.clientHeight;
  }
  const navbar = document.getElementById('navbar');
  if (navbar) {
    height -= navbar.clientHeight;
  }
  height -= 64;
  height = Math.max(height, 256);
  return height;
});

const selectItem = (item: string) => {
  emit('selectItem', item);
};
</script>

<style scoped lang="sass">
.list
  height: v-bind('getHeight')
  overflow-y: auto
</style>
